9
drop table purview CASCADE CONSTRAINTS ;
drop table emp_purview CASCADE CONSTRAINTS ;
drop table report CASCADE CONSTRAINTS ;
drop table animal_index CASCADE CONSTRAINTS ;
drop table emg_H_Msg CASCADE CONSTRAINTS ;
drop table emg_H CASCADE CONSTRAINTS ;
drop table track CASCADE CONSTRAINTS ;
drop table adpPhotos CASCADE CONSTRAINTS ;
drop table adpMsg CASCADE CONSTRAINTS ;
drop table adp CASCADE CONSTRAINTS ;
drop table park CASCADE CONSTRAINTS ;
drop table aniHomePhotos CASCADE CONSTRAINTS ;
drop table aniHomeMsg CASCADE CONSTRAINTS ;
drop table aniHome CASCADE CONSTRAINTS ;
drop table employee CASCADE CONSTRAINTS ;
drop table mem CASCADE CONSTRAINTS ;
drop table charge CASCADE CONSTRAINTS ;
drop table product_kind CASCADE CONSTRAINTS ;
drop table orders_item CASCADE CONSTRAINTS ;
drop table second_ProdPhotos CASCADE CONSTRAINTS ;
drop table second_ProdMsg CASCADE CONSTRAINTS ;
drop table product CASCADE CONSTRAINTS ;
drop table second_Prod CASCADE CONSTRAINTS ;
drop table orders CASCADE CONSTRAINTS ;
CREATE TABLE purview (purview_No VARCHAR2(8),pruview_name VARCHAR2(50), ConStraint purview_PK PRIMARY KEY ( purview_No ) ENABLE );
CREATE TABLE emp_purview (emp_No VARCHAR2(8),purview_No VARCHAR2(8), ConStraint emp_purview_PK PRIMARY KEY ( emp_No , purview_No ) ENABLE );
CREATE TABLE report (report_No VARCHAR2(8),report_name VARCHAR2(30),report_class VARCHAR2(30),report_class_No VARCHAR2(30), ConStraint report_PK PRIMARY KEY ( report_No ) ENABLE );
CREATE TABLE animal_index (animal_No VARCHAR2(8),animal_detail VARCHAR2(300),animal_class VARCHAR2(2),animal_class_No VARCHAR2(2), ConStraint animal_index_PK PRIMARY KEY ( animal_No ) ENABLE );
CREATE TABLE emg_H_Msg (emg_H_Msg_Id VARCHAR2(8),mem_Id VARCHAR2(8),emg_H_Id VARCHAR2(8),emg_H_Msg_start DATE,emg_H_Msg_content VARCHAR2(300) NOT NULL , ConStraint emg_H_Msg_PK PRIMARY KEY ( emg_H_Msg_Id ) ENABLE );
CREATE TABLE emg_H (emg_H_Id VARCHAR2(8),mem_Id VARCHAR2(8),emg_H_start_date DATE,emg_H_end_date DATE,emg_H_title VARCHAR2(90),emg_H_content VARCHAR2(3000),emg_H_Pic BLOB,emg_H_Pic_format VARCHAR2(10),emg_H_city VARCHAR2(20),emg_H_town VARCHAR2(20),emg_H_road VARCHAR2(50),emg_H_Lon NUMBER(9,6),emg_H_Lat NUMBER(9,6), ConStraint emg_H_PK PRIMARY KEY ( emg_H_Id ) ENABLE );
CREATE TABLE track (track_Id VARCHAR2(8),mem_Id VARCHAR2(8),track_record_class VARCHAR2(1),track_record_class_Id VARCHAR2(8), ConStraint track_PK PRIMARY KEY ( track_Id ) ENABLE );
CREATE TABLE adpPhotos (adpPhotos_Id VARCHAR2(8),adp_Id VARCHAR2(8),adpPhotosPic BLOB, ConStraint adpPhotos_PK PRIMARY KEY ( adpPhotos_Id ) ENABLE );
CREATE TABLE adpMsg (adpMsg_Id VARCHAR2(8),adp_Id VARCHAR2(8),mem_Id VARCHAR2(8),msg VARCHAR2(3000),adpMsgDate DATE,adpMsgadp_upDate DATE, ConStraint adpMsg_PK PRIMARY KEY ( adpMsg_Id ) ENABLE );
CREATE TABLE adp (adp_Id VARCHAR2(8),mem_Id VARCHAR2(8),adp_title VARCHAR2(90),adp_adp_content VARCHAR2(3000),adp_start_date DATE,adp_end_date DATE,adp_upDate DATE,adp_city VARCHAR2(12),adp_town VARCHAR2(12),adp_lon VARCHAR2(50),lon NUMBER(9,6),lat NUMBER(9,6), ConStraint adp_PK PRIMARY KEY ( adp_Id ) ENABLE );
CREATE TABLE park (park_Id VARCHAR2(8),emp_Id VARCHAR2(8),title VARCHAR2(90),content VARCHAR2(3000),pic BLOB,adp_start_date DATE,adp_upDate DATE,adp_city VARCHAR2(12),town VARCHAR2(12),road VARCHAR2(50),lon NUMBER(9,6),lat NUMBER(9,6), ConStraint park_PK PRIMARY KEY ( park_Id ) ENABLE );
CREATE TABLE aniHomePhotos (aniHomePhotos_Id VARCHAR2(8),aniHome_Id VARCHAR2(8),pic BLOB, ConStraint aniHomePhotos_PK PRIMARY KEY ( aniHomePhotos_Id ) ENABLE );
CREATE TABLE aniHomeMsg (aniHomeMsg_Id VARCHAR2(8),aniHome_Id VARCHAR2(8),mem_Id VARCHAR2(8),msg VARCHAR2(3000),adp_start_date DATE, ConStraint aniHomeMsg_PK PRIMARY KEY ( aniHomeMsg_Id ) ENABLE );
CREATE TABLE aniHome (aniHome_Id VARCHAR2(8),mem_Id VARCHAR2(8),title VARCHAR2(90),content VARCHAR2(3000),adp_start_date DATE,adp_upDate DATE,adp_city VARCHAR2(12),town VARCHAR2(12),road VARCHAR2(50),lon NUMBER(9,6),lat NUMBER(9,6), ConStraint aniHome_PK PRIMARY KEY ( aniHome_Id ) ENABLE );
CREATE TABLE employee (emp_No VARCHAR2(8),emp_name VARCHAR2(30) NOT NULL ,emp_Pw VARCHAR2(20) NOT NULL ,emp_email VARCHAR2(30),emp_Id VARCHAR2(20),emp_birthday DATE,emp_phone VARCHAR2(15),emp_address VARCHAR2(100),emp_status NUMBER(1),emp_picture BLOB,emp_Pic_format VARCHAR2(10),emp_hiredate DATE NOT NULL ,emp_firedate DATE, ConStraint employee_PK PRIMARY KEY ( emp_No ) ENABLE );
CREATE TABLE mem (mem_Id VARCHAR2(8),mem_account VARCHAR2(60) NOT NULL ,mem_Psw VARCHAR2(60) NOT NULL ,mem_nick_name VARCHAR2(60) NOT NULL ,mem_name VARCHAR2(60) NOT NULL ,mem_gender VARCHAR2(1) NOT NULL ,mem_Tw_Id VARCHAR2(10) NOT NULL ,mem_birth_date DATE NOT NULL ,mem_phone VARCHAR2(60) NOT NULL ,mem_Intro VARCHAR2(150),mem_profile BLOB,mem_black_list VARCHAR2(1),mem_permission VARCHAR2(1),mem_setting VARCHAR2(30),mem_balance NUMBER(10), ConStraint mem_PK PRIMARY KEY ( mem_Id ) ENABLE );
CREATE TABLE charge (charge_no VARCHAR2(8),mem_Id VARCHAR2(8),charge_NUMBER NUMBER(5) NOT NULL ,pay NUMBER(1),applytime DATE NOT NULL , ConStraint charge_PK PRIMARY KEY ( charge_no ) ENABLE );
CREATE TABLE product_kind (product_kind_no VARCHAR2(5),product_kind_name VARCHAR2(10) NOT NULL , ConStraint product_kind_PK PRIMARY KEY ( product_kind_no ) ENABLE );
CREATE TABLE orders_item (orders_no VARCHAR2(8),product_no VARCHAR2(8),commodities_amout NUMBER(5),selling_price NUMBER(5), ConStraint orders_item_PK PRIMARY KEY ( orders_no , product_no ) ENABLE );
CREATE TABLE second_ProdPhotos (second_ProdPhotos_Id VARCHAR2(8),second_Prod_Id VARCHAR2(8) NOT NULL , ConStraint second_ProdPhotos_PK PRIMARY KEY ( second_ProdPhotos_Id ) ENABLE );
CREATE TABLE second_ProdMsg (second_ProdMsg_Id VARCHAR2(8),second_Prod_Id VARCHAR2(8) NOT NULL ,mem_Id VARCHAR2(8) NOT NULL ,second_ProdMsg_Msg VARCHAR2(3000),second_ProdMsg_DATE DATE,second_ProdMsg_adp_upDate DATE, ConStraint second_ProdMsg_PK PRIMARY KEY ( second_ProdMsg_Id ) ENABLE );
CREATE TABLE product (product_no VARCHAR2(8),product_name VARCHAR2(50) NOT NULL ,product_introduction VARCHAR2(300),product_price NUMBER(5) NOT NULL ,product_stock NUMBER(5) NOT NULL ,product_picture_large BLOB,product_picture_small BLOB,product_status NUMBER(1),product_create_date DATE NOT NULL ,product_info VARCHAR2(300),product_kind_no NUMBER(1), ConStraint product_PK PRIMARY KEY ( product_no ) ENABLE );
CREATE TABLE second_Prod (second_Prod_Id VARCHAR2(8),mem_Id VARCHAR2(8),second_Prod_Title VARCHAR2(90),second_Prod_Content VARCHAR2(3000),second_Prod_adp_start_date DATE,second_Prod_adp_end_date DATE,second_Prod_adp_upDate DATE,second_Prod_adp_city VARCHAR2(12),second_Prod_Town VARCHAR2(12),second_Prod_Road VARCHAR2(50),second_Prod_Lon NUMBER(9,6),second_Prod_Lat NUMBER(9,6), ConStraint second_Prod_PK PRIMARY KEY ( second_Prod_Id ) ENABLE );
CREATE TABLE orders (orders_no VARCHAR2(8),mem_Id VARCHAR2(10) NOT NULL ,orders_receiver VARCHAR2(10) NOT NULL ,post_no VARCHAR2(5),post_adp_city VARCHAR2(15) NOT NULL ,post_town VARCHAR2(15) NOT NULL ,post_road VARCHAR2(30) NOT NULL ,orders_phone NUMBER(10) NOT NULL ,collect_mode_no NUMBER(1) NOT NULL ,orders_date DATE NOT NULL ,orders_ship_date DATE,orders_total NUMBER(16),orders_status NUMBER(1),orders_credit NUMBER(16), ConStraint orders_PK PRIMARY KEY ( orders_no ) ENABLE );
COMMENT ON COLUMN purview.purview_No IS '權限編號 | PS: ';
COMMENT ON COLUMN purview.pruview_name IS '權限名稱 | PS: ';
COMMENT ON COLUMN emp_purview.emp_No IS '員工編號 | PS: ';
COMMENT ON COLUMN emp_purview.purview_No IS '權限編號 | PS: ';
COMMENT ON COLUMN report.report_No IS '檢舉編號 | PS: ';
COMMENT ON COLUMN report.report_name IS '檢舉名稱 | PS: ';
COMMENT ON COLUMN report.report_class IS '檢舉類別 | PS: 0.留言
1.文章
2.流浪狗
3.自家寵物
4.揪團活動
5.領養活動';
COMMENT ON COLUMN report.report_class_No IS '檢舉類別編號 | PS: 0.討論區留言
1.討論區文章
2.流浪狗圖鑑留言
3.自家寵物圖鑑留言
3.揪團活動留言
4.領養活動留言
5.緊急求救留言
6.店家留言
7.流浪狗編號
8.自家寵物編號
9. 會員編號
10. 店家編號
11.揪團活動編號
12.領養活動編號
13.緊急求救編號';
COMMENT ON COLUMN animal_index.animal_No IS '圖鑑編號 | PS: ';
COMMENT ON COLUMN animal_index.animal_detail IS '圖鑑敘述 | PS: ';
COMMENT ON COLUMN animal_index.animal_class IS '圖鑑類別 | PS: ';
COMMENT ON COLUMN animal_index.animal_class_No IS '圖鑑類別照片編號 | PS: ';
COMMENT ON COLUMN emg_H_Msg.emg_H_Msg_Id IS '緊急求救留言編號 | PS: ';
COMMENT ON COLUMN emg_H_Msg.mem_Id IS '留言會員編號 | PS: ';
COMMENT ON COLUMN emg_H_Msg.emg_H_Id IS '求救編號 | PS: ';
COMMENT ON COLUMN emg_H_Msg.emg_H_Msg_start IS '發布時間 | PS: ';
COMMENT ON COLUMN emg_H_Msg.emg_H_Msg_content IS '留言內容 | PS: ';
COMMENT ON COLUMN emg_H.emg_H_Id IS '求救編號 | PS: ';
COMMENT ON COLUMN emg_H.mem_Id IS '發起人編號 | PS: ';
COMMENT ON COLUMN emg_H.emg_H_start_date IS '開始時間 | PS: ';
COMMENT ON COLUMN emg_H.emg_H_end_date IS '結束日期 | PS: ';
COMMENT ON COLUMN emg_H.emg_H_title IS '求救標題 | PS: 標題上限字數-30個中文字';
COMMENT ON COLUMN emg_H.emg_H_content IS '求救內容 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN emg_H.emg_H_Pic IS '照片 | PS: ';
COMMENT ON COLUMN emg_H.emg_H_Pic_format IS '照片副檔名 | PS: ';
COMMENT ON COLUMN emg_H.emg_H_city IS '縣市 | PS: 可以為空';
COMMENT ON COLUMN emg_H.emg_H_town IS '鄉鎮市區 | PS: 可以為空';
COMMENT ON COLUMN emg_H.emg_H_road IS '道路街名村里 | PS: 可以為空';
COMMENT ON COLUMN emg_H.emg_H_Lon IS '緊急求救經度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN emg_H.emg_H_Lat IS '緊急求救緯度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN track.track_Id IS '收藏編號 | PS: ';
COMMENT ON COLUMN track.mem_Id IS '會員編號 | PS: ';
COMMENT ON COLUMN track.track_record_class IS '收藏種類 | PS: 0.流浪動物 1.領養活動 2.揪團 3.緊急求救 4.店家 5.二手 6.自家寵物';
COMMENT ON COLUMN track.track_record_class_Id IS '種類編號 | PS: ';
COMMENT ON COLUMN adpPhotos.adpPhotos_Id IS '領養活動相簿編號 | PS: PK';
COMMENT ON COLUMN adpPhotos.adp_Id IS '領養活動編號 | PS: FK';
COMMENT ON COLUMN adpPhotos.adpPhotosPic IS '領養活動照片 | PS: ';
COMMENT ON COLUMN adpMsg.adpMsg_Id IS '領養活動留言編號 | PS: PK';
COMMENT ON COLUMN adpMsg.adp_Id IS '領養活動編號 | PS: FK';
COMMENT ON COLUMN adpMsg.mem_Id IS '留言會員編號 | PS: FK';
COMMENT ON COLUMN adpMsg.msg IS '領養活動留言 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN adpMsg.adpMsgDate IS '留言發布日期 | PS: ';
COMMENT ON COLUMN adpMsg.adpMsgadp_upDate IS '留言更新日期 | PS: 有更新才會有值';
COMMENT ON COLUMN adp.adp_Id IS '領養活動編號 | PS: ';
COMMENT ON COLUMN adp.mem_Id IS '發布會員編號 | PS: ';
COMMENT ON COLUMN adp.adp_title IS '領養活動標題 | PS: 標題上限字數-30個中文字';
COMMENT ON COLUMN adp.adp_adp_content IS '領養活動內容 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN adp.adp_start_date IS '領養活動發布時間 | PS: ';
COMMENT ON COLUMN adp.adp_end_date IS '領養活動到期時間 | PS: ';
COMMENT ON COLUMN adp.adp_upDate IS '領養活動更新時間 | PS: ';
COMMENT ON COLUMN adp.adp_city IS '縣市 | PS: ';
COMMENT ON COLUMN adp.adp_town IS '鄉鎮市區 | PS: ';
COMMENT ON COLUMN adp.adp_lon IS '道路街名村里 | PS: ';
COMMENT ON COLUMN adp.lon IS '領養活動經度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN adp.lat IS '緯度座標緯度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN park.park_Id IS '公園編號 | PS: PK';
COMMENT ON COLUMN park.emp_Id IS '員工編號 | PS: FK';
COMMENT ON COLUMN park.title IS '公園標題 | PS: 標題上限字數-30個中文字';
COMMENT ON COLUMN park.content IS '公園內容 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN park.pic IS '公園照片 | PS: ';
COMMENT ON COLUMN park.adp_start_date IS '公園發布時間 | PS: ';
COMMENT ON COLUMN park.adp_upDate IS '公園更新時間 | PS: ';
COMMENT ON COLUMN park.adp_city IS '縣市 | PS: ';
COMMENT ON COLUMN park.town IS '鄉鎮市區 | PS: ';
COMMENT ON COLUMN park.road IS '道路街名村里 | PS: ';
COMMENT ON COLUMN park.lon IS '公園經度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN park.lat IS '緯度座標緯度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN aniHomePhotos.aniHomePhotos_Id IS '相片編號 | PS: PK';
COMMENT ON COLUMN aniHomePhotos.aniHome_Id IS '動物之家編號 | PS: FK';
COMMENT ON COLUMN aniHomePhotos.pic IS '動物之家照片 | PS: ';
COMMENT ON COLUMN aniHomeMsg.aniHomeMsg_Id IS '動物之家留言編號 | PS: PK';
COMMENT ON COLUMN aniHomeMsg.aniHome_Id IS '動物之家編號 | PS: FK';
COMMENT ON COLUMN aniHomeMsg.mem_Id IS '留言會員編號 | PS: FK';
COMMENT ON COLUMN aniHomeMsg.msg IS '動物之家留言 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN aniHomeMsg.adp_start_date IS '留言發布日期 | PS: ';
COMMENT ON COLUMN aniHome.aniHome_Id IS '動物之家編號 | PS: PK';
COMMENT ON COLUMN aniHome.mem_Id IS '會員編號 | PS: FK';
COMMENT ON COLUMN aniHome.title IS '動物之家標題 | PS: 標題上限字數-30個中文字';
COMMENT ON COLUMN aniHome.content IS '動物之家內容 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN aniHome.adp_start_date IS '動物之家發布時間 | PS: ';
COMMENT ON COLUMN aniHome.adp_upDate IS '動物之家更新時間 | PS: ';
COMMENT ON COLUMN aniHome.adp_city IS '縣市 | PS: ';
COMMENT ON COLUMN aniHome.town IS '鄉鎮市區 | PS: ';
COMMENT ON COLUMN aniHome.road IS '道路街名村里 | PS: ';
COMMENT ON COLUMN aniHome.lon IS '動物之家經度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN aniHome.lat IS '緯度座標緯度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN employee.emp_No IS '員工編號 | PS: ';
COMMENT ON COLUMN employee.emp_name IS '員工姓名 | PS: ';
COMMENT ON COLUMN employee.emp_Pw IS '員工密碼 | PS: ';
COMMENT ON COLUMN employee.emp_email IS '員工信箱 | PS: ';
COMMENT ON COLUMN employee.emp_Id IS '員工身分證 | PS: ';
COMMENT ON COLUMN employee.emp_birthday IS '員工出生年月日 | PS: ';
COMMENT ON COLUMN employee.emp_phone IS '員工電話 | PS: ';
COMMENT ON COLUMN employee.emp_address IS '員工地址 | PS: ';
COMMENT ON COLUMN employee.emp_status IS '員工狀態 | PS: 1:在職 0: 離職';
COMMENT ON COLUMN employee.emp_picture IS '員工照片 | PS: ';
COMMENT ON COLUMN employee.emp_Pic_format IS '員工照片副檔名 | PS: ';
COMMENT ON COLUMN employee.emp_hiredate IS '雇用日期 | PS: ';
COMMENT ON COLUMN employee.emp_firedate IS '離職日期 | PS: ';
COMMENT ON COLUMN mem.mem_Id IS '會員編號 | PS: PK';
COMMENT ON COLUMN mem.mem_account IS '帳號 | PS: 電子信箱就是帳號';
COMMENT ON COLUMN mem.mem_Psw IS '密碼 | PS: ';
COMMENT ON COLUMN mem.mem_nick_name IS '會員暱稱 | PS: ';
COMMENT ON COLUMN mem.mem_name IS '姓名 | PS: ';
COMMENT ON COLUMN mem.mem_gender IS '性別 | PS: M.男F.女';
COMMENT ON COLUMN mem.mem_Tw_Id IS '身份證字號 | PS: ';
COMMENT ON COLUMN mem.mem_birth_date IS '出生年月日 | PS: ';
COMMENT ON COLUMN mem.mem_phone IS '手機 | PS: ';
COMMENT ON COLUMN mem.mem_Intro IS '個人簡介 | PS: ';
COMMENT ON COLUMN mem.mem_profile IS '大頭照 | PS: ';
COMMENT ON COLUMN mem.mem_black_list IS '黑名單 | PS: 0.非黑名單1.黑名單';
COMMENT ON COLUMN mem.mem_permission IS '權限 | PS: 1.一般 2.志工 3.店家';
COMMENT ON COLUMN mem.mem_setting IS '偏好設定 | PS: 0.流浪動物 1.領養活動 2.揪團 3.緊急求救 4.店家 5.二手 6.自家寵物';
COMMENT ON COLUMN mem.mem_balance IS '餘額 | PS: ';
COMMENT ON COLUMN charge.charge_no IS '儲值編號 | PS: ';
COMMENT ON COLUMN charge.mem_Id IS '會員編號 | PS: ';
COMMENT ON COLUMN charge.charge_NUMBER IS '儲值金額 | PS: ';
COMMENT ON COLUMN charge.pay IS '付款方式 | PS: 1.ATM 2.超商';
COMMENT ON COLUMN charge.applytime IS '儲值時間 | PS: ';
COMMENT ON COLUMN product_kind.product_kind_no IS '商品類別編號 | PS: ';
COMMENT ON COLUMN product_kind.product_kind_name IS '商品類別名稱 | PS: NOT NULL';
COMMENT ON COLUMN orders_item.orders_no IS '訂單編號 | PS: ';
COMMENT ON COLUMN orders_item.product_no IS '商品編號 | PS: ';
COMMENT ON COLUMN orders_item.commodities_amout IS '訂購數量 | PS: ';
COMMENT ON COLUMN orders_item.selling_price IS '商品售價 | PS: ';
COMMENT ON COLUMN second_ProdPhotos.second_ProdPhotos_Id IS '二手商品相簿編號 | PS: ';
COMMENT ON COLUMN second_ProdPhotos.second_Prod_Id IS '二手商品編號 | PS: ';
COMMENT ON COLUMN second_ProdMsg.second_ProdMsg_Id IS '二手商品留言編號 | PS: ';
COMMENT ON COLUMN second_ProdMsg.second_Prod_Id IS '二手商品編號 | PS: ';
COMMENT ON COLUMN second_ProdMsg.mem_Id IS '留言會員編號 | PS: ';
COMMENT ON COLUMN second_ProdMsg.second_ProdMsg_Msg IS '二手商品留言 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN second_ProdMsg.second_ProdMsg_DATE IS '留言發布日期 | PS: ';
COMMENT ON COLUMN second_ProdMsg.second_ProdMsg_adp_upDate IS '留言更新日期 | PS: 有更新才會有值';
COMMENT ON COLUMN product.product_no IS '商品編號 | PS: ';
COMMENT ON COLUMN product.product_name IS '商品名稱 | PS: ';
COMMENT ON COLUMN product.product_introduction IS '商品簡介 | PS: ';
COMMENT ON COLUMN product.product_price IS '商品價格 | PS: ';
COMMENT ON COLUMN product.product_stock IS '商品庫存量 | PS: ';
COMMENT ON COLUMN product.product_picture_large IS '商品圖片 | PS: ';
COMMENT ON COLUMN product.product_picture_small IS '商品圖片（縮圖） | PS: ';
COMMENT ON COLUMN product.product_status IS '商品上下架狀態 | PS: 1.上架2.下架';
COMMENT ON COLUMN product.product_create_date IS '商品建立日期 | PS: ';
COMMENT ON COLUMN product.product_info IS '商品資訊 | PS: ';
COMMENT ON COLUMN product.product_kind_no IS '商品類別編號 | PS: ';
COMMENT ON COLUMN second_Prod.second_Prod_Id IS '二手商品編號 | PS: ';
COMMENT ON COLUMN second_Prod.mem_Id IS '發布會員編號 | PS: ';
COMMENT ON COLUMN second_Prod.second_Prod_Title IS '二手商品標題 | PS: 標題上限字數-30個中文字';
COMMENT ON COLUMN second_Prod.second_Prod_Content IS '二手商品內容 | PS: 內容上限字數-1000個中文字';
COMMENT ON COLUMN second_Prod.second_Prod_adp_start_date IS '二手商品發布時間 | PS: ';
COMMENT ON COLUMN second_Prod.second_Prod_adp_end_date IS '二手商品截止時間 | PS: 到期刪除二手商品地圖圖標、資訊';
COMMENT ON COLUMN second_Prod.second_Prod_adp_upDate IS '二手商品更新時間 | PS: ';
COMMENT ON COLUMN second_Prod.second_Prod_adp_city IS '縣市 | PS: 可以為空';
COMMENT ON COLUMN second_Prod.second_Prod_Town IS '鄉鎮市區 | PS: 可以為空';
COMMENT ON COLUMN second_Prod.second_Prod_Road IS '道路街名村里 | PS: 可以為空';
COMMENT ON COLUMN second_Prod.second_Prod_Lon IS '二手商品經度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN second_Prod.second_Prod_Lat IS '緯度座標緯度座標 | PS: 由住址分析出來，或手機抓GPS取得(有小數點)';
COMMENT ON COLUMN orders.orders_no IS '訂單編號 | PS: ';
COMMENT ON COLUMN orders.mem_Id IS '會員編號 | PS: ';
COMMENT ON COLUMN orders.orders_receiver IS '收件人 | PS: ';
COMMENT ON COLUMN orders.post_no IS '郵遞區號 | PS: ';
COMMENT ON COLUMN orders.post_adp_city IS '縣市 | PS: ';
COMMENT ON COLUMN orders.post_town IS '鄉鎮 | PS: ';
COMMENT ON COLUMN orders.post_road IS '路 | PS: ';
COMMENT ON COLUMN orders.orders_phone IS '收件人電話 | PS: ';
COMMENT ON COLUMN orders.collect_mode_no IS '付款方式 | PS: ';
COMMENT ON COLUMN orders.orders_date IS '下單日期 | PS: ';
COMMENT ON COLUMN orders.orders_ship_date IS '出貨日期 | PS: ';
COMMENT ON COLUMN orders.orders_total IS '總金額 | PS: ';
COMMENT ON COLUMN orders.orders_status IS '處理狀態 | PS: 1處理中2.已完成';
COMMENT ON COLUMN orders.orders_credit IS '信用卡卡號 | PS: ';
ALTER TABLE emp_purview ADD CONSTRAINT emp_purview_FK1 FOREIGN KEY ( emp_No ) REFERENCES emp ( emp_No ) ENABLE;
ALTER TABLE emp_purview ADD CONSTRAINT emp_purview_FK2 FOREIGN KEY ( purview_No ) REFERENCES purview ( purview_No ) ENABLE;
ALTER TABLE emg_H_Msg ADD CONSTRAINT emg_H_Msg_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE emg_H_Msg ADD CONSTRAINT emg_H_Msg_FK2 FOREIGN KEY ( emg_H_Id ) REFERENCES emg_H ( emg_H_Id ) ENABLE;
ALTER TABLE emg_H ADD CONSTRAINT emg_H_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE track ADD CONSTRAINT track_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE adpMsg ADD CONSTRAINT adpMsg_FK1 FOREIGN KEY ( adp_Id ) REFERENCES adp ( adp_Id ) ENABLE;
ALTER TABLE adpMsg ADD CONSTRAINT adpMsg_FK2 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE adp ADD CONSTRAINT adp_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE park ADD CONSTRAINT park_FK1 FOREIGN KEY ( emp_Id ) REFERENCES emp ( emp_No ) ENABLE;
ALTER TABLE aniHomePhotos ADD CONSTRAINT aniHomePhotos_FK1 FOREIGN KEY ( aniHome_Id ) REFERENCES aniHome ( aniHome_Id ) ENABLE;
ALTER TABLE aniHomeMsg ADD CONSTRAINT aniHomeMsg_FK1 FOREIGN KEY ( aniHome_Id ) REFERENCES aniHome ( aniHome_Id ) ENABLE;
ALTER TABLE aniHomeMsg ADD CONSTRAINT aniHomeMsg_FK2 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE aniHome ADD CONSTRAINT aniHome_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE charge ADD CONSTRAINT charge_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE orders_item ADD CONSTRAINT orders_item_FK1 FOREIGN KEY ( orders_no ) REFERENCES orders ( orders_no ) ENABLE;
ALTER TABLE orders_item ADD CONSTRAINT orders_item_FK2 FOREIGN KEY ( product_no ) REFERENCES product ( product_no ) ENABLE;
ALTER TABLE second_ProdPhotos ADD CONSTRAINT second_ProdPhotos_FK1 FOREIGN KEY ( second_Prod_Id ) REFERENCES second_Prod ( second_Prod_Id ) ENABLE;
ALTER TABLE second_ProdMsg ADD CONSTRAINT second_ProdMsg_FK1 FOREIGN KEY ( second_Prod_Id ) REFERENCES second_Prod ( second_Prod_Id ) ENABLE;
ALTER TABLE second_ProdMsg ADD CONSTRAINT second_ProdMsg_FK2 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE second_Prod ADD CONSTRAINT second_Prod_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
ALTER TABLE orders ADD CONSTRAINT orders_FK1 FOREIGN KEY ( mem_Id ) REFERENCES mem ( mem_Id ) ENABLE;
