--------------------------------------------------------
--  鄭群部分  
--------------------------------------------------------

CREATE SEQUENCE stray_Ani_Seq INCREMENT BY 1 START WITH 20000001 NOMAXVALUE;
CREATE SEQUENCE adopt_Ani_Seq INCREMENT BY 1 START WITH 40000001 NOMAXVALUE;
CREATE SEQUENCE pet_Seq INCREMENT BY 1 START WITH 30000001 NOMAXVALUE;
CREATE SEQUENCE stray_Ani_photos_Seq INCREMENT BY 1 START WITH 21000001 NOMAXVALUE;
CREATE SEQUENCE stray_Ani_message_Seq INCREMENT BY 1 START WITH 22000001 NOMAXVALUE;
CREATE SEQUENCE stray_Ani_Loc_Seq INCREMENT BY 1 START WITH 23000001 NOMAXVALUE;
CREATE SEQUENCE pet_photos_Seq INCREMENT BY 1 START WITH 31000001 NOMAXVALUE;
CREATE SEQUENCE pet_message_Seq INCREMENT BY 1 START WITH 32000001 NOMAXVALUE;
CREATE SEQUENCE adopt_Ani_photos_Seq INCREMENT BY 1 START WITH 41000001 NOMAXVALUE;
CREATE SEQUENCE adopt_Ani_message_Seq INCREMENT BY 1 START WITH 42000001 NOMAXVALUE;
CREATE SEQUENCE adopt_Ani_sponsor_Seq INCREMENT BY 1 START WITH 43000001 NOMAXVALUE;